version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:latest
    # restart: always
    environment:
      # database url to connect
      HASURA_GRAPHQL_DATABASE_URL: FILL_ME_IN 
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: FILL_ME_IN
    command:
    - graphql-engine 
    - serve
    ports:
    - 8080
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - 80
    - 443
    - 2015
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs: